version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-kot-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: ep-dark-heart-ayr83462.c-5.us-east-2.aws.neon.tech
      DB_PORT: 5432
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_yvWYurwd0HT9
      DB_DATABASE: neondb
      DB_SSL: "true"
      JWT_SECRET: super_secret_jwt_key_change_me_in_production
      JWT_EXPIRATION: 24h
      SEED_ADMIN_EMAIL: admin@cafekot.com
      SEED_ADMIN_PASSWORD: AdminSecurePassword123!
      GST_RATE: 5
    command: >
      sh -c "npm run db:migrate:prod && npm run db:seed:prod && npm run start:prod"

volumes:
  pgdata:
